kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/mnteiei/azure/krub"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: afstorage
