kind: Pod
apiVersion: v1
metadata:
  name: mypod2
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/mntei/azure/krubqweqwe"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azurefile
