version: "3"
services:
  web:
    image: sregistry.azurecr.io/geoweb_server:1.10
    container_name: web_server
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "80:80"
    links: 
      - mysql

  mysql:
    image: sregistry.azurecr.io/mysql_server:1.10
    container_name: mysql_server
    restart: always
    ports:
      - "8889:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=mysql
    container_name: phpmyadmin
    ports:
      - "8080:80"
    links: 
      - mysql
