apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.10.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spark-master
    spec:
      containers:
      - args:
        - echo
        - "$spark-master"
        # - bin/spark-class
        # - org.apache.spark.deploy.master.Master
        # - -h
        # - spark-master
        env:
        - name: MASTER
          value: spark://spark-master:7077
        - name: SPARK_CONF_DIR
          value: /conf
        # - name: SPARK_PUBLIC_DNS
        #   value: 192.168.99.100
        image: registryz.azurecr.io/spark:2.20
        name: spark-master
        ports:
        - containerPort: 4040
        - containerPort: 6066
        - containerPort: 7077
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: eiei
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.10.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  ports:
  - name: "4040"
    port: 4040
    targetPort: 4040
  - name: "6066"
    port: 6066
    targetPort: 6066
  - name: "7077"
    port: 7077
    targetPort: 7077
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: spark-master
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.10.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker-1
  name: spark-worker-1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spark-worker-1
    spec:
      containers:
      - args:
        - bin/spark-class
        - org.apache.spark.deploy.worker.Worker
        - spark://spark-master:7077
        env:
        - name: SPARK_CONF_DIR
          value: /conf
        - name: SPARK_WORKER_CORES
          value: "2"
        - name: SPARK_WORKER_MEMORY
          value: 2g
        - name: SPARK_WORKER_PORT
          value: "8881"
        - name: SPARK_WORKER_WEBUI_PORT
          value: "8081"
        image: registryz.azurecr.io/spark:2.20
        name: spark-worker-1
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: eiei
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.10.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker-1
  name: spark-worker-1
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: spark-worker-1
status:
  loadBalancer: {}
